//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrewTurn.Wiki.Plugins.Oracle.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrewTurn.Wiki.Plugins.Oracle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;script_collections&gt;
        ///
        ///  &lt;script&gt;
        ///    &lt;![CDATA[
        ///    CREATE TABLE Directory
        ///    (
        ///       FullPath   VARCHAR2 (250) NOT NULL,
        ///       Parent     VARCHAR2 (250),
        ///       CONSTRAINT PK_Directory PRIMARY KEY (FullPath)
        ///    )
        ///    ]]&gt;
        ///  &lt;/script&gt;
        ///
        ///  &lt;script&gt;
        ///    &lt;![CDATA[
        ///    CREATE TABLE &quot;File&quot;
        ///    (
        ///       Name           VARCHAR2 (200) NOT NULL,
        ///       Directory      VARCHAR2 (250)
        ///             NOT NULL
        ///             CONSTRAINT FK_File_Directory
        ///           [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string FilesDatabase {
            get {
                return ResourceManager.GetString("FilesDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;script_collections&gt;
        ///
        ///  &lt;script&gt;
        ///    &lt;![CDATA[
        ///    CREATE TABLE Namespace
        ///    (
        ///       Name          VARCHAR2 (100) NOT NULL,
        ///       DefaultPage   VARCHAR2 (200),
        ///       CONSTRAINT PK_Namespace PRIMARY KEY (Name)
        ///    )
        ///    ]]&gt;
        ///  &lt;/script&gt;
        ///
        ///  &lt;script&gt;
        ///    &lt;![CDATA[
        ///    CREATE TABLE Category
        ///    (
        ///       Name        VARCHAR2 (100) NOT NULL,
        ///       Namespace   VARCHAR2 (100) NOT NULL,
        ///       CONSTRAINT PK_Category PRIMARY KEY (Name, Namespace)
        ///    )
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PagesDatabase {
            get {
                return ResourceManager.GetString("PagesDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;script_collections&gt;
        ///
        ///  &lt;script&gt;
        ///    &lt;![CDATA[DROP TABLE IndexWordMapping  CASCADE CONSTRAINTS]]&gt;
        ///  &lt;/script&gt;
        ///  &lt;script&gt;
        ///    &lt;![CDATA[  DROP TABLE IndexWord CASCADE CONSTRAINTS]]&gt;
        ///  &lt;/script&gt;
        ///  &lt;script&gt;
        ///    &lt;![CDATA[DROP TABLE IndexDocument CASCADE CONSTRAINTS]]&gt;
        ///  &lt;/script&gt;
        ///  &lt;script&gt;
        ///    &lt;![CDATA[
        ///  CREATE TABLE IndexDocument
        ///  (
        ///  Id         NUMBER (18, 0) NOT NULL,
        ///  Name       VARCHAR2 (200) NOT NULL CONSTRAINT UQ_IndexDocument UNIQUE,
        ///  Title    [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PagesDatabase_3000to3001 {
            get {
                return ResourceManager.GetString("PagesDatabase_3000to3001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;script_collections&gt;
        ///  &lt;!--script type=&quot;proc|text&quot; default text--&gt;
        ///  &lt;script&gt;
        ///    &lt;![CDATA[
        ///CREATE TABLE Setting
        ///(
        ///   Name    VARCHAR (100) NOT NULL,
        ///   Value   VARCHAR2 (4000) NOT NULL,
        ///   CONSTRAINT PK_Setting PRIMARY KEY (Name)
        ///)
        ///]]&gt;
        ///  &lt;/script&gt;
        ///
        ///  &lt;script&gt;
        ///    &lt;![CDATA[
        ///CREATE TABLE Log
        ///(
        ///   Id            NUMBER (18, 0) NOT NULL,
        ///   DateTime    DATE NOT NULL,
        ///   EntryType   CHAR NOT NULL,
        ///   &quot;User&quot;        VARCHAR2 (100) NOT NULL,
        ///   Message    [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SettingsDatabase {
            get {
                return ResourceManager.GetString("SettingsDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;script_collections&gt;
        ///
        ///  &lt;script&gt;
        ///    &lt;![CDATA[
        ///    CREATE TABLE &quot;User&quot;
        ///    (
        ///       Username       VARCHAR2 (100) NOT NULL,
        ///       PasswordHash   VARCHAR2 (100) NOT NULL,
        ///       DisplayName    VARCHAR2 (150),
        ///       Email          VARCHAR2 (100) NOT NULL,
        ///       Active         INT NOT NULL,
        ///       DateTime       DATE NOT NULL,
        ///       CONSTRAINT PK_User PRIMARY KEY (Username)
        ///    )
        ///    ]]&gt;
        ///  &lt;/script&gt;
        ///
        ///  &lt;script&gt;
        ///    &lt;![CDATA[
        ///    CREATE TABLE UserGr [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UsersDatabase {
            get {
                return ResourceManager.GetString("UsersDatabase", resourceCulture);
            }
        }
    }
}
